### PR TITLE
 Issue_7_layout_for_home_page

### PR DESCRIPTION
**Pull request by KT0601**
Issue: 7

 7 
#### Short description of what this resolves:
 ------>      Figma design of layout of home page

#### Changes proposed in this pull request and/or Screenshots of changes:
------>  Contain home_layout.txt file in homepage/Design folder. In this file there is a link of figma file.
Screenshot (307)

### CODE REVIEW

**Comment by Adi-R12** [comment]
@KT0601 give access !

**Comment by yashg-116** [comment]
> Issue: 7
> 
> 7
> #### Short description of what this resolves:
> ------> Figma design of layout of home page
> 
> #### Changes proposed in this pull request and/or Screenshots of changes:
> ## ------> Contain home_layout.txt file in homepage/Design folder. In this file there is a link of figma file.

@KT0601 You have to give access to figma file otherwise your PR won't be accepted.

**Comment by Adi-R12** [comment]
@KT0601 try to improve your colour theme.. date is extended by tomorrow

**Comment by KT0601** [comment]
> @KT0601 try to improve your colour theme.. date is extended by tomorrow you can take reference from merged pr of hero section

I have made some changes. can you review it

**Comment by KT0601** [comment]
@Adi-R12

**Pull request closed without merging**
