### PR TITLE
Re-Create Navbar 

### PR DESCRIPTION
**Pull request by Kali-Decoder**
Issue: 65

#### Short description of what this resolves:

Create New Navbar as per design for web View 

#### Changes proposed in this pull request and/or Screenshots of changes:
recreate navbar

-
-
-

### CODE REVIEW

**Comment by yashg-116** [comment]
@Kali-Decoder It seemed like you have done it in a hurry
Many changes are needed
1. Color palette is not same as given in figma link
2. community icon is not matching
3. message icon is not there
4. only the current page button (eg. home) should be primary 
5. image should have some border radius

**Comment by yashg-116** [comment]
@Kali-Decoder you have time till 12 O' noon tomorrow.

**Comment by Kali-Decoder** [comment]
- Color Palette is Done 
- Community Icon is done 
- message icon is placed 
- current page is primary done 
- image has border radius and text is bold done
- box shadow is done  
@yashg-116

**Comment by Adi-R12** [comment]
@Kali-Decoder route the buttons in navbar and make them primary on click(colour change)

**Pull request merged**
