### PR TITLE
Navbar Bugs Removed

### PR DESCRIPTION
**Pull request by Kali-Decoder**
Issue: 72

#### Short description of what this resolves:

Navbar errors rectified 

#### Changes proposed in this pull request and/or Screenshots of changes:

-Mobile View Of Navbar
navbar-mobile

-Web View Of Navbar
navbar-web

-

### CODE REVIEW

**Comment by yashg-116** [comment]
@Kali-Decoder you didn't have to change the website view of navbar. Previous was better.
navbar

Besides, you have not added search icon in search box in navbar webite view, also you have not done routing (linking pages) in navbar.
In mobile view, first of all navbar should open vertically, where instead of icons, full names(e.g. Home, Commmunities, Chat, Profile, Signout) should be there.
Also a search icon will be there beside hamburger icon in navbar itself in mobile screen view which should expand on clicking to open search box.

**Comment by yashg-116** [comment]
For any further doubts, you can ping us on Discord.

**Comment by yashg-116** [comment]
updates?

**Comment by Kali-Decoder** [comment]
Doing Bhaiya

**Comment by Kali-Decoder** [comment]
Done

**Pull request closed without merging**
