### PR TITLE
Home-page

### PR DESCRIPTION
**Pull request by ananyaa07**
Issue: 7

### CODE REVIEW

**Comment by Adi-R12** [comment]
@ananyaa07  spacing aur alignment theek nahi hai, aur jo bottom right hai voh khaali lag raha

**Comment by Adi-R12** [comment]
@ananyaa07 spacing 4 ke multiples mai honi chahiye

**Comment by ananyaa07** [comment]
I am working on it

**Comment by ananyaa07** [comment]
@Adi-R12 I have done the required changes

**Pull request merged**
